export type MainCategory = 'MY_PAGE' | 'APPROVAL' | 'RESERVATION' | 'BOARD' | 'REQUEST' | 'CONTACT';

export type SubView = 
  // MY_A9
  | 'DASHBOARD' | 'PROFILE' | 'CALENDAR' | 'VACATION' | 'VACATION_REQUEST' | 'ORG_CHART' | 'WORK_SPEC' | 'OKR'
  // APPROVAL
  | 'APPROVAL_WRITE' | 'APPROVAL_RECEIVED' | 'APPROVAL_SENT'
  // RESERVATION
  | 'RESERVATION_HOME' | 'HEALTHCARE' | 'MEETING_ROOM' | 'VEHICLE' | 'RESORT' | 'CAFETERIA' | 'CAMPING'
  // BOARD
  | 'BOARD_HOME' | 'COLLECTIVE' | 'ION' | 'SUBSIDIARY_B' | 'SUBSIDIARY_C'
  // REQUEST
  | 'REQUEST_HOME' | 'PURCHASE' | 'CERTIFICATE' | 'PURCHASE_DETAIL' | 'CERTIFICATE_DETAIL'
  // CONTACT
  | 'CONTACT_EMPLOYEE' | 'CONTACT_RETIRED' | 'CONTACT_CLIENT';
